---
title: "Segunda clase"
author: "Eugenio Gómez"
date: "`r Sys.Date()`"
output: html_document
---

```{r here}
library(here)
dir.create(here("data", "raw"), recursive = TRUE)
```

```{r}
library(tidyverse)
cinco <- 5
vec <- c(5:8)
oper <- sqrt(4)
otraoper <- cinco + oper
leyenda <- "pantera no cualquiera"
```

```{r}
weo <- read_csv(here("data", "raw", "WEOapr2026.csv"))
```

```{r}
library(readxl)
gapminder <- read_excel(path = here("data", "raw", "gapminder.xlsx"), col_names = TRUE)
```

## Filter

```{r}
filter(gapminder, lifeExp < 50, year == 2007, continent != "Africa")
```



```{r tipo de cambio}
library(siebanxicor) # cargar banxico
tokenbanxico = "722cbe96cb081225e74de97e4d37a564cf9d4d72d44701b772a3dfc8a8055383"
# siebanxicor
setToken(tokenbanxico) # esto es así
idSeries <- c("SF343410")
tc <- getSeriesData(idSeries,
                   "2023-01-01",
                    Sys.Date())
datosbanxico <- getSerieDataFrame(tc, "SF343410")
```


```{r PIBEUA, include=FALSE}
library(fredr)
fredr_set_key("bf6a6d9ade210364071b4810d5635c59")
pibusa <- fredr(series_id = "GDPC1",
                      observation_start = as.Date("2000-01-01"),
                      units = "pc1")
```


```{r el bueno función, include=FALSE}
inegi_series <- function(indicador, token) {
  library(httr)
  library(jsonlite)
  library(rjson)
  
  #Llamado al API
  url <- paste0("https://www.inegi.org.mx/app/api/indicadores/desarrolladores/jsonxml/INDICATOR/",
                indicador, "/es/00/false/BIE-BISE/2.0/", token, "?type=json")
  respuesta<-GET(url)
  datosGenerales<-content(respuesta,"text")
  flujoDatos<-paste(datosGenerales,collapse = " ")
  
        if (status_code(respuesta) != 200) {
      warning("Error al descargar indicador: ", indicador)
      return(NULL)
      }
  
  #Obtención de la lista de observaciones 
  flujoDatos<-fromJSON(flujoDatos)
  flujoDatos<-flujoDatos $Series
  flujoDatos<-flujoDatos[[1]] $OBSERVATIONS
  
  # Extraer fecha y valor de cada elemento usando sapply
  fechas <- sapply(flujoDatos, function(x) x$TIME_PERIOD)
  valores <- sapply(flujoDatos, function(x) x$OBS_VALUE)
  
  # Crear data frame
  df <- data.frame(
    date = fechas,
    values = as.numeric(valores)
  )
  
  # Formato de fecha
  # Extraer el número después del "/"
  periodo <- as.numeric(substr(df$date, 6, 7))
  
  # Si hay algún valor > 4, es mensual; si no, es trimestral
  es_mensual <- max(periodo) > 4
  
  if (es_mensual) {
    df <- df %>%
      mutate(date = as.Date(paste0(date, "/01"), format = "%Y/%m/%d"))
  } else {
    df <- df %>%
      mutate(
        año = as.numeric(substr(date, 1, 4)),
        trimestre = as.numeric(substr(date, 6, 7)),
        mes = (trimestre - 1) * 3 + 1,
        date = as.Date(paste(año, mes, "01", sep = "-"))
      ) %>%
      select(-año, -trimestre, -mes)
  }
  
  
  # Ordenar cronológicamente
  df <- df[order(df$date), ]
  rownames(df) <- NULL

  return(df)
}

```


```{r el bueno función múltiples series, include=FALSE}

inegi_series_multiple <- function(indicadores, token) {
  
  # Si es un solo indicador, convertir a vector
  if (length(indicadores) == 1) {
    indicadores <- setNames(indicadores, indicadores)
  }

inegi_series <- function(indicador, token) {
  library(httr)
  library(jsonlite)
  library(rjson)

    #Llamado al API
  url <- paste0("https://www.inegi.org.mx/app/api/indicadores/desarrolladores/jsonxml/INDICATOR/",
                indicador, "/es/00/false/BIE-BISE/2.0/", token, "?type=json")
  respuesta<-GET(url)
  datosGenerales<-content(respuesta,"text")
  flujoDatos<-paste(datosGenerales,collapse = " ")
  
        if (status_code(respuesta) != 200) {
      warning("Error al descargar indicador: ", indicador)
      return(NULL)
      }
  
  #Obtención de la lista de observaciones 
  flujoDatos<-fromJSON(flujoDatos)
  flujoDatos<-flujoDatos $Series
  flujoDatos<-flujoDatos[[1]] $OBSERVATIONS
  
  # Extraer fecha y valor de cada elemento usando sapply
  fechas <- sapply(flujoDatos, function(x) x$TIME_PERIOD)
  valores <- sapply(flujoDatos, function(x) x$OBS_VALUE)
  
  # Crear data frame
  df <- data.frame(
    date = fechas,
    values = as.numeric(valores)
  )
  
  # Formato de fecha
  # Extraer el número después del "/"
  periodo <- as.numeric(substr(df$date, 6, 7))
  
  # Si hay algún valor > 4, es mensual; si no, es trimestral
  es_mensual <- max(periodo) > 4
  
  if (es_mensual) {
    df <- df %>%
      mutate(date = as.Date(paste0(date, "/01"), format = "%Y/%m/%d"))
  } else {
    df <- df %>%
      mutate(
        año = as.numeric(substr(date, 1, 4)),
        trimestre = as.numeric(substr(date, 6, 7)),
        mes = (trimestre - 1) * 3 + 1,
        date = as.Date(paste(año, mes, "01", sep = "-"))
      ) %>%
      select(-año, -trimestre, -mes)
  }
  
  # Ordenar cronológicamente
  df <- df[order(df$date), ]
  rownames(df) <- NULL

  return(df)
}

 # Descargar todas las series
  lista_series <- lapply(indicadores, inegi_series, token = token)
  
  # Eliminar series que fallaron
  lista_series <- lista_series[!sapply(lista_series, is.null)]
  
  df_completo <- bind_rows(lista_series, .id = "serie")
  return(df_completo)
  
  return(lista_series)
}
```



```{r datosinflacion, include=FALSE}
inegiapi <- "2842b8e5-a899-63af-cc62-dccaca5fa8db"
datos <- c("1general" = "910392", "2subyacente" = "910393", "3mercancias" = "910394", "4servicios" = "910395", "5nosubyacente" = "910396", "6agropecuarios" = "910397", "7energeticos" = "910398") 
inflaciondata <- inegi_series_multiple(datos, inegiapi)  
```


