---
title: "C"
author: "Eugenio Gómez"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
library(tidyverse)
library(here)
gapminder <- read_csv(here("gapminder.csv"))
```



```{r}
ggplot(gapminder, aes(x = gdpPercap, y = lifeExp))

```



```{r}
ggplot(gapminder, aes(x = gdpPercap, y = lifeExp)) + geom_point()
```


```{r}
datos1992 <- filter(gapminder, year==1992
                    )
```


```{r}
ggplot(datos1992, aes(x = gdpPercap, y = lifeExp)) + geom_point(color="seagreen3")
```


```{r}
ggplot(datos1992, aes(x = gdpPercap, y = lifeExp, color=continent, size=pop)) + geom_point()
```


```{r}
ggplot(datos1992, aes(x = gdpPercap, y = lifeExp, color=continent, size=pop)) + geom_point() +
  scale_x_log10()
```

```{r}
ggplot(datos1992, aes(x = gdpPercap, y = lifeExp, color=continent, size=pop)) + geom_point() +
  scale_x_log10() +
  facet_wrap(vars(continent))
```




```{r}
ggplot(datos1992, aes(x = gdpPercap, y = lifeExp, color=continent, size=pop)) + geom_point() +
  scale_x_log10() +
  labs(title="Esperanza de vida vs PIB per capita", subtitle = "Datos de 1992", x = "PIB per cápita", y ="Esperanza de vida", color = "Continente", size = "Población", caption = "Fuente: The Gapminder project")
```

```{r}
ggplot(datos1992, aes(x = gdpPercap, y = lifeExp, color=continent, size=pop)) + geom_point() +
  scale_x_log10() +
  labs(title="Esperanza de vida vs PIB per capita", subtitle = "Datos de 1992", x = "PIB per cápita", y ="Esperanza de vida", color = "Continente", size = "Población", caption = "Fuente: The Gapminder project") +
  theme_bw()
```


```{r}
datosmexico <- filter(gapminder, country == "Mexico")
```

```{r}
ggplot(datosmexico, aes(x=year, y= gdpPercap)) +
  geom_line(color= "#015B51", linetype = "dashed") +
  geom_point(color= "#015B51") +
  theme_minimal()
```

```{r}
datoseuropa <- filter(gapminder, continent == "Europe", year == 2007, gdpPercap >= 35000)
```


```{r}
ggplot(datoseuropa, aes(x=reorder(country, -gdpPercap), y=gdpPercap)) +
  geom_col(fill="blue")
```






















